### ISSUE TITLE
Graphic design

### ISSUE THREAD

**Issue by trc11231** [2miners/Proposals#1]
# Proposal

I can do some design =)

# Description

Hi, I'm a graphic designer. And I can help you with creating Facebook and Twitter blog covers, related to your corporate style. If you have any questions, feel free for ask them.

# Funding goal

The payment: 0.1 ETH for every cover

My address is 0x7bFb999D36f083175A1C9caa9Ea6FFA3BeF58757

**Comment by sneg55** [comment]
Sounds good, we need cover images for our twitter and facebook accounts. 

you can find our logos here: https://2miners.com/about 

0x8ec6fe7819bc4f9ce440890b3cee9d6888bd0a98eaf77ff64deba82b2126baa7

**Comment by olimpkzdev** [comment]
These are not real miners, that's real. 😃 
![image](https://user-images.githubusercontent.com/40725252/45198536-50192180-b267-11e8-83de-ed62ef4c107b.png)
