### ISSUE TITLE
Web/Mobile Developer

### ISSUE THREAD

**Issue by MichelKansou** [2miners/Proposals#2]
# Proposal

I can work on my free time on web app (front-end) or mobile app (iOS)

# Description

Hi, I'm a software developer I have multiple experiences in Web and Mobile app (ReactJS, Angular 5, Swift). I can help you with fixing bugs, creating new features or even creating a mobile app 😉. If you have any questions, feel free to ask anything.

# Funding goal
The payment depends on what is the task, I accept payment in ETH, ETC or LTC

LTC : LgDEkNWafXxcmq7hDP7kxokZZGZttvTchT
ETH : 0xE25E8239A4550a1B9D44B798Ea52E9d90BC7A2b3
ETC : 0xea6CD5A4aa622348eE0758117c043da1C1BE52d9

**Comment by sneg55** [comment]
What about your hourly rate for front-end tasks?

**Comment by MichelKansou** [comment]
1 ETC per hour for front end 🙂
