### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by vehsika** [2miners/Proposals#3]
# Proposal

Hi, I can make a app for 2miners under android and even publish it in the play market ;)

# Description

You have a very good api, on its basis I could make applications for easy monitoring

# Funding goal

2 ETH. One time payment. My address is 0xd6D4d83B4021D8B08B82fe69625B485b06C2A0C4

**Comment by DuDlikSPB** [comment]
Any example of your work?

**Comment by olimpkzdev** [comment]
http://bit.do/ewnuQ
http://bit.do/ewnva
http://bit.do/ewnvf

**Comment by olimpkzdev** [comment]
I can do it first, and then pay as much as you want 🤙

**Comment by DuDlikSPB** [comment]
Any example of your work?

**Comment by olimpkzdev** [comment]
https://play.google.com/store/apps/details?id=kz.naimi.app
