### ISSUE TITLE
2miners PHP SDK Package

### ISSUE THREAD

**Issue by sv3tli0** [2miners/Proposals#4]
# Proposal

I can build full PHP SDK for 2miners API.

# Description

I can build a full PHP SDK for 2miners API - this will provide many developers with ability to easily connect to your API with all of its pools.
It will have proper documentation and php unit tests.

# Funding goal

1ETH - one time payment
0x453cC2B431eb27de0741457D423b78a80c77108C

**Comment by DuDlikSPB** [comment]
Thanx, you didn't get idea of mining pools.

**Comment by sv3tli0** [comment]
I got the idea.. :)
Just in my case it would be easier to monitor/track all the pools I use if there were sdk's instead of making API mapping for each one of them (although most of the pools have quite similar api's).
That's why I gave that proposal here.

Good luck :)
